#!/bin/bash
# (c) Stefan Countryman 2017
# the aliases i use

# use `nd` instead of `cd` to allow for `fwd` and `back` plus bookmarks use
alias cd=nd

# some ipython profile aliases
alias ipy='ipython'
alias imath='ipython --profile=math'
alias iastro='ipython --profile=astro'
alias igrace='ipython --profile=grace'
alias igwpy='ipython --profile=gwpy'
alias illama='ipython --profile=gwhen'
alias iheavy='ipython --profile=heavy'

alias bfg="java -jar '${HOME}'/dev/dotfiles/static/bfg-1.13.0.jar"

# edit my passwords file
alias secrets='cp ~/Dropbox/crypt/.netrc{,.backup} && cp ~/{Dropbox/crypt/,}.netrc.backup && vim ~/Dropbox/crypt/.netrc'

# add color to some utilities
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# two-sided print
alias lpdub="lp -o sides=two-sided-long-edge"

# vim aliases prevent XQuartz from opening and allow for GPG vim plugin use
add_vim_environ(){
    for cmd in "$@"; do
        alias ${cmd}="DISPLAY='' ${cmd}"
    done
}
add_vim_environ view vi vim vimdiff vimtutor

# gotta use signal-cli
alias signal=~/dev/dotfiles/submodules/signal-cli/build/install/signal-cli/bin/signal-cli

# get battry info
alias batt='pmset -g batt'

# url encode and decode from stdin
alias urlencode="python2 -c 'import urllib, sys; sys.stdout.write(urllib.quote(sys.stdin.read()))'"
alias urldecode="python2 -c 'import urllib, sys; sys.stdout.write(urllib.unquote(sys.stdin.read()))'"
alias htmlencode="python3 -c 'import sys; sys.stdout.write(sys.stdin.read().encode(\"ascii\", \"xmlcharrefreplace\").decode(\"ascii\"))'"
alias queryencode="python2 -c 'import urllib, sys; sys.stdout.write(urllib.quote_plus(sys.stdin.read()))'"
alias querydecode="python2 -c 'import urllib, sys; sys.stdout.write(urllib.unquote_plus(sys.stdin.read()))'"
alias urlrename='for f in *; do mv "$f" $(echo $f | urlencode); done'
alias urlunname='for f in *; do mv "$f" $(echo $f | urldecode); done'
alias queryrename='for f in *; do mv "$f" $(echo $f | queryencode); done'
alias queryunname='for f in *; do mv "$f" $(echo $f | querydecode); done'

# workaround; vim saves files in a way that pisses off crontab
alias crontab="VIM_CRONTAB=true crontab"

# shortcut for non-gui matlab
alias matcli='matlab -no{splash,desktop,jvm}'

# shortcut for php composer
if [[ -f ~/bin/composer.phar ]]; then
    alias composer="php "~/"bin/composer.phar"
fi
