#!/bin/bash
# (c) Stefan Countryman 2017-2020
# the aliases i use

# use `nd` instead of `cd` to allow for `fwd` and `back` plus bookmarks use
alias cd=nd

# some ipython profile aliases
alias imath='ipython --profile=math'
alias iastro='ipython --profile=astro'
alias igrace='ipython --profile=grace'
alias igwpy='ipython --profile=gwpy'
alias illama='ipython --profile=gwhen'
alias iheavy='ipython --profile=heavy'

alias bfg="java -jar '${HOME}'/dev/dotfiles/static/bfg-1.14.0.jar"

# edit my passwords file
alias secrets='cp ~/Dropbox/crypt/.netrc{,.backup} && cp ~/{Dropbox/crypt/,}.netrc.backup && vim ~/Dropbox/crypt/.netrc'

# add color to some utilities
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# vim aliases prevent XQuartz from opening and allow for GPG vim plugin use
add_vim_environ(){
    for cmd in "$@"; do
        alias ${cmd}="DISPLAY='' ${cmd}"
    done
}
add_vim_environ view vi vim vimdiff vimtutor

# gotta use signal-cli
# alias signal=~/dev/dotfiles/submodules/signal-cli/build/install/signal-cli/bin/signal-cli

# workaround; vim saves files in a way that pisses off crontab
alias crontab="VIM_CRONTAB=true crontab"

# shortcut for non-gui matlab
alias matcli='matlab -no{splash,desktop,jvm}'

# shortcut for php composer
if [[ -f ~/bin/composer.phar ]]; then
    alias composer="php "~/"bin/composer.phar"
fi
