#!/bin/bash
# (c) Stefan Countryman (2018)

b32pass() {
    if [ $# -ne 1 ]; then
        echo >&2 "must provide exactly one arg (number of character in string)"
        return 1
    fi
    python -c 'import textwrap; exec(textwrap.dedent(r"""
        # A function for printing a base32 password (just lowercase numbers and
        # letters) using cryptographically secure random bits.
        from sys import argv
        from os import urandom
        from base64 import b32encode as b32

        plen = int(argv[1])
        print(b32(urandom(plen*5//8+1))[:plen].lower().decode())
    """+" "*4))' "$@"
}
