#!/bin/bash
# (c) Stefan Countryman (2018)

b32pass() {
    python -c 'import textwrap; exec(textwrap.dedent(r"""
        # A function for printing a base32 password (just lowercase numbers and
        # letters) using cryptographically secure random bits.
        import sys, os, base64
        plen = int(sys.argv[1])
        print(base64.b32encode(os.urandom(plen*5//8))[:plen].lower().decode())
    """+" "*4))' "$@"
}
