#!/bin/bash
# (c) Stefan Countryman 2024

__emacsd_procs () {
    printf %s "${procs}"
}

__emacsd_procs_found () {
    [[ $(__emacsd_procs | wc -c) -gt 0 ]] && return 0 || return 1
}

emacsd () {
    local HELP='Start up the emacs daemon; `l` to list existing, `k` to kill existing'
    local MIN_NODE_VERSION=20
    local l=0
    local k=0
    local l_or_k
    local procs

    # Parse args
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            l|li|lis|list)
                l=1
                shift
                ;;
            k|ki|kil|kill)
                k=1
                shift
                ;;
            *)
                echo "${HELP}"
                return 1
                ;;
        esac
    done

    # Handle listing or killing
    l_or_k=$((l + k))
    if [[ ${l_or_k} -gt 0 ]]; then
        procs="$(ps -ax | grep 'emacs.*--daemon' | sed '/grep/d')"
    fi
    if [[ ${l} -eq 1 ]]; then
        __emacsd_procs_found && (__emacsd_procs; echo)
    fi
    if [[ ${k} -eq 1 ]]; then
        __emacsd_procs_found \
            && (
                __emacsd_procs | sed 's/^ *//' | cut -d ' ' -f 1 | xargs kill
                printf >&2 'Killed:\n%s\n' "${procs}"
            ) \
            || echo >&2 'No emacs daemon procs found.'
    fi
    if [[ ${l_or_k} -gt 0 ]]; then
        __emacsd_procs_found && return 0 || return 1
    fi

    # Start the daemon
    (
        # Use Anaconda for CMake LSP support
        source "$HOME/anaconda3/bin/activate"
        conda activate emacs
        # Make sure to use proper node if available (for LSP)
        if (type node >/dev/null 2>&1); then
            local node_version="$(node --version | cut -d . -f 1 | tr -dc '[0-9]')"
            if [[ ${node_version} -lt ${MIN_NODE_VERSION} ]]; then
                echo >&2 "Detected bad node version ${node_version}..."
                if (type nvm >/dev/null 2>&1); then
                    echo >&2 "Using NVM to set node version to ${MIN_NODE_VERSION}"
                    nvm use "${MIN_NODE_VERSION}"
                else
                    echo >&2 "WARNING: node version ${node_version} is too old for LSP and no \`nvm\` detected"
                fi
            else
                echo >&2 "Found valid node version ${node_version} for LSP"
            fi
        else
            echo >&2 'WARNING: `node` command not found, LSP will not work'
        fi
        echo >&2 'Starting emacs daemon...'
        emacs --daemon
    )
}
