#!/bin/bash
# (c) Stefan Countryman (2018)
# Some Linux-specific crap. Most of this breaks if you load in non-Linux.

# welcome message
if [ "`hostname`" = "gamagori" ]; then
    cat ${DOTFILEDIR}/static/gamagori.txt
fi
