#!/bin/bash

# Run initialization code specific to `motoko` and `motoko2` MacOS disk images.
# This should be called from `macos` if the hostname as returned by
# `scutil --get ComputerName` is `motoko`.

# print the welcome ASCII art
# cat ${DOTFILEDIR}/static/motoko-banner.txt
# echo "Welcome to motoko2."

# test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

condas() {
    export CONDAS=1
    dotsource motoko-conda
}

ligo() {
    if [[ "$CONDAS" -ne 1 ]]; then
        echo 'Setting up Conda with `condas`'
        condas
    fi
    conda activate ligo-py36
}
