#!/bin/bash

# Run initialization code specific to `motoko` and `motoko2` MacOS disk images.
# This should be called from `macos` if the hostname as returned by
# `scutil --get ComputerName` is `motoko`.

# print the welcome ASCII art
# cat ${DOTFILEDIR}/static/motoko-banner.txt
# echo "Welcome to motoko2."
# cat ${DOTFILEDIR}/static/kong.txt
cat ${DOTFILEDIR}/static/misato/small-misato.txt

# test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

condas() {
    export CONDAS=1
    eval "$(/Users/s/anaconda3/bin/conda shell.bash hook)"
}

llamas() {
    if [[ "$CONDAS" -ne 1 ]]; then
        echo 'Setting up Conda with `condas`'
        condas
    fi
    conda activate llama-py37
}

# added by travis gem
[ -f /Users/s/.travis/travis.sh ] && source /Users/s/.travis/travis.sh
