#!/bin/bash
# (c) Stefan Countryman 2017
# initialize PATH variable

# user-specific executables:
export PATH="${DOTFILEDIR}/bin:$PATH"
export PATH=~/"bin:$PATH"

# GECo-specific executables:
for geco_repo in geco_data geco_channel geco_plots; do
    export PATH=~/dev/"$geco_repo:$PATH"
done

# get a better PATH (only if `pathsorter` executable exists for this purpose)
type -f 1>/dev/null 2>&1 pathsorter \
    && export PATH="$(pathsorter llama mactex user pg11 cargo py27 py37 py35 py36 py34 port macvim sys pyuser py36usermac dyalog drawterm)"

# # put ~/lib in the C library path
export C_INCLUDE_PATH=~/include:"$C_INCLUDE_PATH"
export LIBRARY_PATH=~/lib:"$LIBRARY_PATH"
