#!/bin/bash
# (c) Stefan Countryman, 2017
# Set env variables for q console

if [[ $OSTYPE == darwin* ]]; then
    if [ "`scutil --get ComputerName`" = "Alexis Nelson’s MacBook Pro" ]; then
        export QHOME=~/bin
        export QLIC=~/lic/kc.lic
    fi
fi
