#!/bin/bash
# (c) Stefan Countryman 2017
# create a quicklook alias for quicklooking at files
if [[ $SESSION_TYPE == remote/ssh ]]; then
    echo "quick look not yet enabled."
else
    alias ql="qlmanage -p 1>/dev/null 2>&1"
fi

