#!/bin/bash
# (c) Stefan Countryman 2017
# If a command corresponds to a file, open that file for editing in vim.

vimex () {
    local cmdtype
    if ! cmdtype="$(type 2>/dev/null "$1")"; then
        echo >&2 "Command not found."
        return 1
    elif [[ $cmdtype == "$1 is aliased to"* ]]; then
        echo >&2 "Command is an alias, cannot edit."
        return 2
    elif [[ $cmdtype == "$1 is a function"* ]]; then
        echo >&2 "Command is a function, cannot edit."
        return 3
    fi
    vim "${cmdtype/$1 is /}"
}
