#!/bin/bash
# (c) Stefan Countryman 2017
# If a command corresponds to a file, open that file for editing in vim.

vimex () {
    local cmdtype
    local cmd
    if ! cmdtype="$(type 2>/dev/null "$1")"; then
        echo >&2 "Command not found."
        return 1
    elif [[ $cmdtype == "$1 is aliased to"* ]]; then
        echo >&2 "Command is an alias, cannot edit."
        return 2
    elif [[ $cmdtype == "$1 is a function"* ]]; then
        echo >&2 "Command is a function, cannot edit."
        return 3
    elif [[ $cmdtype == "$1 is hashed ("* ]]; then
        cmd="${cmdtype#$1 is hashed (}"
        cmd="${cmd%)}"
    else
        cmd="${cmdtype#$1 is }"
    fi
    vim "$cmd"
}

# `vimex` autocompletion; http://www.tldp.org/LDP/abs/html/tabexpansion.html
# details on `complete` and `compgen` builtins:
# https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html
complete -c vimex
