#!/usr/bin/env python
# (c) Stefan Countryman (2018)


"""
The on-add event is triggered separately for each task added. This hook
script can accept/reject the addition. Processing will continue.
"""

import sys
import json

# Input:
# - line of JSON for the added task.
new = json.loads(sys.stdin.readline().strip())
info = ""

def has_tag(task, tag):
    """Check whether a task contains a tag."""
    if "tags" not in task:
        return False
    return tag in task['tags']

# If "buy" tag exists, put in Buy trello list.
if has_tag(new, "buy"):
    new["intheamtrellolistname"] = "Buy"
    info += ("'{}' -> 'Buy' trello list. ").format(new["description"])

# Output:
# - JSON, modified or unmodified.
# - Optional feedback/error.
print(json.dumps(new))
sys.stdout.write(info)

# Status:
# - 0:     JSON accepted, non-JSON is feedback.
# - non-0: JSON ignored, non-JSON is error.
exit(0)
