#!/usr/bin/env python
# (c) Stefan Countryman (2018)


"""
The on-modify event is triggered separately for each task modified. This hook
script can accept/reject the modification. Processing will continue.
"""

import sys
import json

# Input:
# - line of JSON for the original task
# - line of JSON for the modified task, the diff being the modification
original = json.loads(sys.stdin.readline().strip())
modified = json.loads(sys.stdin.readline().strip())
info = ""

def has_tag(task, tag):
    """Check whether a task contains a tag."""
    if "tags" not in task:
        return False
    return tag in task['tags']

# If "buy" was not in the original, put this in the buy list
if has_tag(modified, "buy") and not has_tag(original, "buy"):
    modified["intheamtrellolistname"] = "Buy"
    info += ("'{}' -> 'Buy' trello list. ").format(modified["description"])

# Output:
# - JSON, modified or unmodified.
# - Optional feedback/error.
print(json.dumps(modified))
sys.stdout.write(info)

# Status:
# - 0:     JSON accepted, non-JSON is feedback.
# - non-0: JSON ignored, non-JSON is error.
exit(0)
